### ISSUE TITLE
[FEATURE] tree.json -> tree.yaml

### ISSUE THREAD

**Issue by douglasvinter** [ZupIT/ritchie-formulas#20]
**What would you like to be added**:

I think moving the JSON structure to a YAML would be more of a benefit in terms of visualization and adopting a Map structure instead of Array

Note: "The code wise", "Command Listing" is how I see the logic behind, didn't checked the source code before suggesting this

Code wise: Array[i].parent > Recursive til parent command (validation)
Command Listing: for ... { add(parent.contains(key)) }

Regular JSON structure

```
{
   "commands":[
      {
         "usage":"aws",
         "help":"Apply Aws objects",
         "parent":"root"
      },
      {
         "usage":"apply",
         "help":"Apply Aws objects",
         "parent":"root_aws"
      },
      {
         "usage":"terraform",
         "help":"Apply Aws terraform objects",
         "formula":{
            "path":"aws/terraform",
            "bin":"terraform-cli-${so}",
            "repoUrl":"http://ritchie-cli-bucket152849730126474.s3-website-sa-east-1.amazonaws.com/formulas/aws/terraform"
         },
         "parent":"root_aws_apply"
      }
   ],
   "version":"1.0.0-dev"
}
```

Code wise: commands->aws->terraform
for sub commands: commands->aws->terraform->commands->load

Command listing: key.child, key.child.values()

New YAML structure

```
version: 1.0.0-dev
commands:
  aws:
    help: Apply Aws objects
    commands:
      apply:
        help: Apply Aws objects
      terraform:
        help: Apply Aws terraform objects
        formula:
          path: aws/terraform
          bin: 'terraform-cli-${so}'
          repoUrl: http://ritchie-cli-bucket152849730126474.s3-website-sa-east-1.amazonaws.com/formulas/aws/terraform
```
				

**Why is this needed**:

- The current structure makes you search over an array to find whatever you need, also you need to build a parent key using a snake_case every, which can be avoiding by just using its command key like the YAML example
